name: template
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  retrofit: ^1.3.4+1
  json_annotation:
  connectivity: ^2.0.2
  dio: ^3.0.10
  flutter_dotenv: ^3.1.0

  sembast: ^2.4.9
  sqflite: ^1.3.2+2
  path: ^1.7.0
  path_provider: ^1.6.27

  get: ^3.24.0
  dartz: ^0.9.2


  kiwi: ^2.1.1
  google_fonts: ^1.1.2

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^1.4.1+2
  build_runner: ^1.11.1
  kiwi_generator: ^2.1.1
  json_serializable: ^3.5.1

flutter:

  uses-material-design: true

  assets:
    - .env
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
